export const colorList = [
  { hex: "#F0F8FF", en: "AliceBlue", vi: "Xanh da trời" },
  { hex: "#FAEBD7", en: "AntiqueWhite", vi: "Kem cổ" },
  { hex: "#00FFFF", en: "Aqua", vi: "Xanh ngọc" },
  { hex: "#7FFFD4", en: "Aquamarine", vi: "Xanh ngọc lam" },
  { hex: "#F0FFFF", en: "Azure", vi: "Xanh lam nhạt" },
  { hex: "#F5F5DC", en: "Beige", vi: "Be" },
  { hex: "#FFE4C4", en: "Bisque", vi: "Be hồng" },
  { hex: "#000000", en: "Black", vi: "Đen" },
  { hex: "#FFEBCD", en: "BlanchedAlmond", vi: "Vàng ngà" },
  { hex: "#0000FF", en: "Blue", vi: "Xanh da trời" },
  { hex: "#8A2BE2", en: "BlueViolet", vi: "Tím xanh" },
  { hex: "#A52A2A", en: "Brown", vi: "Nâu" },
  { hex: "#DEB887", en: "Burlywood", vi: "Vàng đất" },
  { hex: "#5F9EA0", en: "CadetBlue", vi: "Xanh da trời" },
  { hex: "#7FFF00", en: "Chartreuse", vi: "Xanh vàng" },
  { hex: "#D2691E", en: "Chocolate", vi: "Nâu sô cô la" },
  { hex: "#FF7F50", en: "Coral", vi: "Cam san hô" },
  { hex: "#6495ED", en: "CornflowerBlue", vi: "Xanh ngọc" },
  { hex: "#FFF8DC", en: "Cornsilk", vi: "Vàng ngô nhạt" },
  { hex: "#DC143C", en: "Crimson", vi: "Đỏ thẫm" },
  { hex: "#00FFFF", en: "Cyan", vi: "Xanh ngọc" },
  { hex: "#00008B", en: "DarkBlue", vi: "Xanh da trời đậm" },
  { hex: "#008B8B", en: "DarkCyan", vi: "Xanh lơ đậm" },
  { hex: "#B8860B", en: "DarkGoldenrod", vi: "Vàng hoe đậm" },
  { hex: "#A9A9A9", en: "DarkGray", vi: "Xám đậm" },
  { hex: "#006400", en: "DarkGreen", vi: "Xanh lá đậm" },
  { hex: "#A9A9A9", en: "DarkGrey", vi: "Xám đậm" },
  { hex: "#BDB76B", en: "DarkKhaki", vi: "Vàng kaki đậm" },
  { hex: "#8B008B", en: "DarkMagenta", vi: "Hồng thẫm" },
  { hex: "#556B2F", en: "DarkOliveGreen", vi: "Xanh ô liu đậm" },
  { hex: "#FF8C00", en: "DarkOrange", vi: "Cam đậm" },
  { hex: "#9932CC", en: "DarkOrchid", vi: "Tím ngọc đậm" },
  { hex: "#8B0000", en: "DarkRed", vi: "Đỏ đậm" },
  { hex: "#E9967A", en: "DarkSalmon", vi: "Cam đào đậm" },
  { hex: "#8FBC8F", en: "DarkSeaGreen", vi: "Xanh ngọc đậm" },
  { hex: "#483D8B", en: "DarkSlateBlue", vi: "Xanh đen đậm" },
  { hex: "#2F4F4F", en: "DarkSlateGray", vi: "Xám xanh đậm" },
  { hex: "#2F4F4F", en: "DarkSlateGrey", vi: "Xám xanh đậm" },
  { hex: "#00CED1", en: "DarkTurquoise", vi: "Xanh ngọc đậm" },
  { hex: "#9400D3", en: "DarkViolet", vi: "Tím đậm" },
  { hex: "#FF1493", en: "DeepPink", vi: "Hồng đậm" },
  { hex: "#00BFFF", en: "DeepSkyBlue", vi: "Xanh da trời đậm" },
  { hex: "#696969", en: "DimGray", vi: "Xám đậm" },
  { hex: "#696969", en: "DimGrey", vi: "Xám đậm" },
  { hex: "#1E90FF", en: "DodgerBlue", vi: "Xanh da trời" },
  { hex: "#B22222", en: "FireBrick", vi: "Đỏ gạch" },
  { hex: "#FFFAF0", en: "FloralWhite", vi: "Trắng hoa" },
  { hex: "#228B22", en: "ForestGreen", vi: "Xanh lục" },
  { hex: "#FF00FF", en: "Fuchsia", vi: "Hồng cánh sen" },
  { hex: "#DCDCDC", en: "Gainsboro", vi: "Xám nhạt" },
  { hex: "#F8F8FF", en: "GhostWhite", vi: "Trắng ma" },
  { hex: "#FFD700", en: "Gold", vi: "Vàng" },
  { hex: "#DAA520", en: "Goldenrod", vi: "Vàng hoe" },
  { hex: "#808080", en: "Gray", vi: "Xám" },
  { hex: "#008000", en: "Green", vi: "Xanh lá cây" },
  { hex: "#ADFF2F", en: "GreenYellow", vi: "Vàng lục" },
  { hex: "#808080", en: "Grey", vi: "Xám" },
  { hex: "#F0FFF0", en: "HoneyDew", vi: "Trắng ngọc nhạt" },
  { hex: "#FF69B4", en: "HotPink", vi: "Hồng nóng" },
  { hex: "#CD5C5C", en: "IndianRed", vi: "Đỏ đất" },
  { hex: "#4B0082", en: "Indigo", vi: "Chàm" },
  { hex: "#FFFFF0", en: "Ivory", vi: "Ngà" },
  { hex: "#F0E68C", en: "Khaki", vi: "Vàng nhạt" },
  { hex: "#E6E6FA", en: "Lavender", vi: "Tím oải hương" },
  { hex: "#FFF0F5", en: "LavenderBlush", vi: "Tím oải hương nhạt" },
  { hex: "#7CFC00", en: "LawnGreen", vi: "Xanh cỏ" },
  { hex: "#FFFACD", en: "LemonChiffon", vi: "Vàng chanh nhạt" },
  { hex: "#ADD8E6", en: "LightBlue", vi: "Xanh da trời nhạt" },
  { hex: "#F08080", en: "LightCoral", vi: "Hồng san hô nhạt" },
  { hex: "#E0FFFF", en: "LightCyan", vi: "Xanh ngọc nhạt" },
  { hex: "#FAFAD2", en: "LightGoldenrodYellow", vi: "Vàng hoe nhạt" },
  { hex: "#D3D3D3", en: "LightGray", vi: "Xám nhạt" },
  { hex: "#90EE90", en: "LightGreen", vi: "Xanh lá nhạt" },
  { hex: "#D3D3D3", en: "LightGrey", vi: "Xám nhạt" },
  { hex: "#FFB6C1", en: "LightPink", vi: "Hồng nhạt" },
  { hex: "#FFA07A", en: "LightSalmon", vi: "Cam nhạt" },
  { hex: "#20B2AA", en: "LightSeaGreen", vi: "Xanh nước biển nhạt" },
  { hex: "#87CEFA", en: "LightSkyBlue", vi: "Xanh da trời nhạt" },
  { hex: "#778899", en: "LightSlateGray", vi: "Xám xanh nhạt" },
  { hex: "#778899", en: "LightSlateGrey", vi: "Xám xanh nhạt" },
  { hex: "#B0C4DE", en: "LightSteelBlue", vi: "Xanh thép nhạt" },
  { hex: "#FFFFE0", en: "LightYellow", vi: "Vàng nhạt" },
  { hex: "#00FF00", en: "Lime", vi: "Xanh chanh" },
  { hex: "#32CD32", en: "LimeGreen", vi: "Xanh lá chanh" },
  { hex: "#FAF0E6", en: "Linen", vi: "Kem" },
  { hex: "#FF00FF", en: "Magenta", vi: "Hồng tươi" },
  { hex: "#800000", en: "Maroon", vi: "Đỏ hạt dẻ" },
  { hex: "#66CDAA", en: "MediumAquaMarine", vi: "Xanh ngọc vừa" },
  { hex: "#0000CD", en: "MediumBlue", vi: "Xanh dương" },
  { hex: "#BA55D3", en: "MediumOrchid", vi: "Tím hoa lan vừa" },
  { hex: "#9370DB", en: "MediumPurple", vi: "Tím nhạt" },
  { hex: "#3CB371", en: "MediumSeaGreen", vi: "Xanh ngọc" },
  { hex: "#7B68EE", en: "MediumSlateBlue", vi: "Xanh đen vừa" },
  { hex: "#00FA9A", en: "MediumSpringGreen", vi: "Xanh lục sáng vừa" },
  { hex: "#48D1CC", en: "MediumTurquoise", vi: "Xanh ngọc vừa" },
  { hex: "#C71585", en: "MediumVioletRed", vi: "Hồng tím trung bình" },
  { hex: "#191970", en: "MidnightBlue", vi: "Xanh đen" },
  { hex: "#F5FFFA", en: "MintCream", vi: "Trắng mint" },
  { hex: "#FFE4E1", en: "MistyRose", vi: "Hồng phấn nhạt" },
  { hex: "#FFE4B5", en: "Moccasin", vi: "Vàng kem" },
  { hex: "#FFDEAD", en: "NavajoWhite", vi: "Da" },
  { hex: "#000080", en: "Navy", vi: "Xanh dương đậm" },
  { hex: "#FDF5E6", en: "OldLace", vi: "Kem cổ" },
  { hex: "#808000", en: "Olive", vi: "Xanh ô liu" },
  { hex: "#6B8E23", en: "OliveDrab", vi: "Xanh ô liu sẫm" },
  { hex: "#FFA500", en: "Orange", vi: "Cam" },
  { hex: "#FF4500", en: "OrangeRed", vi: "Cam đỏ" },
  { hex: "#DA70D6", en: "Orchid", vi: "Tím lan" },
  { hex: "#EEE8AA", en: "PaleGoldenrod", vi: "Vàng hoe nhạt" },
  { hex: "#98FB98", en: "PaleGreen", vi: "Xanh lục nhạt" },
  { hex: "#AFEEEE", en: "PaleTurquoise", vi: "Xanh ngọc nhạt" },
  { hex: "#DB7093", en: "PaleVioletRed", vi: "Hồng tím nhạt" },
  { hex: "#FFEFD5", en: "PapayaWhip", vi: "Vàng da cam nhạt" },
  { hex: "#FFDAB9", en: "PeachPuff", vi: "Hồng đào nhạt" },
  { hex: "#CD853F", en: "Peru", vi: "Nâu đỏ" },
  { hex: "#FFC0CB", en: "Pink", vi: "Hồng" },
  { hex: "#DDA0DD", en: "Plum", vi: "Mận" },
  { hex: "#B0E0E6", en: "PowderBlue", vi: "Xanh nhạt" },
  { hex: "#800080", en: "Purple", vi: "Tím" },
  { hex: "#663399", en: "RebeccaPurple", vi: "Tím Rebecca" },
  { hex: "#FF0000", en: "Red", vi: "Đỏ" },
  { hex: "#BC8F8F", en: "RosyBrown", vi: "Nâu hồng" },
  { hex: "#4169E1", en: "RoyalBlue", vi: "Xanh chàm" },
  { hex: "#8B4513", en: "SaddleBrown", vi: "Nâu yên ngựa" },
  { hex: "#FA8072", en: "Salmon", vi: "Cam" },
  { hex: "#F4A460", en: "SandyBrown", vi: "Nâu cát" },
  { hex: "#2E8B57", en: "SeaGreen", vi: "Xanh ngọc" },
  { hex: "#FFF5EE", en: "SeaShell", vi: "Trắng ngọc trai" },
  { hex: "#A0522D", en: "Sienna", vi: "Nâu đỏ" },
  { hex: "#C0C0C0", en: "Silver", vi: "Bạc" },
  { hex: "#87CEEB", en: "SkyBlue", vi: "Xanh da trời" },
  { hex: "#6A5ACD", en: "SlateBlue", vi: "Xanh đen" },
  { hex: "#708090", en: "SlateGray", vi: "Xám xanh" },
  { hex: "#708090", en: "SlateGrey", vi: "Xám xanh" },
  { hex: "#FFFAFA", en: "Snow", vi: "Trắng tuyết" },
  { hex: "#00FF7F", en: "SpringGreen", vi: "Xanh lục sáng" },
  { hex: "#4682B4", en: "SteelBlue", vi: "Xanh thép" },
  { hex: "#D2B48C", en: "Tan", vi: "Vàng bò" },
  { hex: "#008080", en: "Teal", vi: "Xanh lơ đậm" },
  { hex: "#D8BFD8", en: "Thistle", vi: "Tím thạch thảo" },
  { hex: "#FF6347", en: "Tomato", vi: "Đỏ cà chua" },
  { hex: "#40E0D0", en: "Turquoise", vi: "Xanh ngọc" },
  { hex: "#EE82EE", en: "Violet", vi: "Tím" },
  { hex: "#F5DEB3", en: "Wheat", vi: "Vàng lúa" },
  { hex: "#FFFFFF", en: "White", vi: "Trắng" },
  { hex: "#F5F5F5", en: "WhiteSmoke", vi: "Trắng khói" },
  { hex: "#FFFF00", en: "Yellow", vi: "Vàng" },
  { hex: "#9ACD32", en: "YellowGreen", vi: "Vàng lục" },
];
